# Generated by Django 5.2.7 on 2025-10-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_alter_note_options_remove_note_tags_notebook_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='name',
        ),
    ]
