# Generated by Django 5.2.7 on 2025-10-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0006_pomodorosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='key_concepts',
        ),
    ]
